version: '3.3'
services:
    web:
        image: scplatform/php8.0:latest
        env_file:
            - .docker.env.local
        volumes:
            - .:/var/www/html
            - ./codedeploy/conf/application.conf:/etc/httpd/conf.d/application.conf
            - ./docker/conf/ssl.conf:/etc/httpd/conf.d/ssl.conf
        depends_on:
            - db
        links:
            - db
    db:
        image: mysql:5.7
        volumes:
            - db_data:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=db
            - MYSQL_USER=user
            - MYSQL_PASSWORD=pass

volumes:
    db_data:
